Implemented pnpm and fixed tests
DeskproApps/app-sdk pull request #7
Opened 2023-01-11 17:53 UTC by iTweeno

2023-01-11 18:12 UTC, AshleyDawson requested changes
Please update README.md docs to reflect use of pnpm

2023-01-12 07:36 UTC, zpawn commented on package.json
>      "lint": "yarn eslint --ext ts,tsx ./src"
Change scripts to use `pnpm`

2023-01-12 08:16 UTC, zpawn commented
I think need to remove the `yarn.lock`

2023-01-12 09:19 UTC, iTweeno commented
@AshleyDawson

2023-01-12 09:20 UTC, AshleyDawson commented
> @AshleyDawson

@iTweeno if you hit the "re-review" button I'll get an alert :) 

![image](https://user-images.githubusercontent.com/1968942/212027711-61bb8445-88eb-4301-af71-88cd2e3a8d2d.png)

2023-01-12 09:22 UTC, AshleyDawson approved these changes

2023-01-12 09:23 UTC, iTweeno commented
Am dumb lol

2023-01-12 09:23 UTC, merged